# Generated by Django 5.0.7 on 2024-07-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vtes',
            new_name='votes',
        ),
    ]
